name: qns
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  flutter_screen_recording: ^2.0.24
  http: ^1.4.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+9
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  android_intent_plus: ^5.3.0
  device_info_plus: ^10.1.0
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  share_plus: ^7.0.0
  just_audio: ^0.10.3
  ffmpeg_kit_flutter_new_gpl: any
  video_player: ^2.9.5
  file_picker: ^10.1.9
  image: ^4.5.4
  screenshot: ^2.1.0
  android_alarm_manager_plus: ^4.0.7
  video_thumbnail: ^0.5.3
  uuid: ^4.5.1
  provider: ^6.1.5
  path_provider: ^2.0.2
  rxdart: ^0.28.0
  crop_your_image: ^0.7.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/quotes_seed.json
    - assets/audio/
    - assets/fonts/
    
    

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
