// lib/constant.dart

const String kQuoteKey = 'quote';
const String kAuthorKey = 'author';
const String kCategory = 'category';

// Add this line (replace with your actual API key if needed)
const String pixabayKey = '50180577-5f0d84f67bd57fb18ae937c93';

// Add this: List of all categories (match with your HomeScreen)
const List<String> kAllQuoteCategories = [
  'All',
  'Action',
  'Adventure',
  'Art',
  'Balance',
  'Belief',
  'Change',
  'Charity',
  'Childhood',
  'Community',
  'Confidence',
  'Courage',
  'Creativity & Inspiration',
  'Culture',
  'Decision',
  'Determination',
  'Discipline',
  'Diversity',
  'Dreams',
  'Education',
  'Empathy',
  'Endings',
  'Equality',
  'Faith',
  'Family',
  'Focus',
  'Forging Ahead',
  'Forgiveness',
  'Freedom',
  'Friendship',
  'Giving',
  'Gratitude',
  'Growth',
  'Hard Work',
  'Happiness & Joy',
  'Health',
  'Hope',
  'Honesty',
  'Humility',
  'Humor',
  'Imagination',
  'Inclusion',
  'Innovation',
  'Integrity',
  'Justice',
  'Kindness',
  'Leadership',
  'Learning',
  'Legacy',
  'Life',
  'Listening',
  'Love',
  'Memories',
  'Mindfulness',
  'Mindfulness & Letting Go',
  'Mindset',
  'Motivation & Achievement',
  'Music',
  'Natural',
  'New Beginnings',
  'Opportunity',
  'Overcoming Obstacles',
  'Parenting',
  'Passion',
  'Patience',
  'Peace',
  'Peace & Inner Calm',
  'Perseverance',
  'Philosophy',
  'Positivity',
  'Prosperity',
  'Purpose',
  'Reflection',
  'Relationships & Connection',
  'Resilience',
  'Responsibility',
  'Risk',
  'Sacrifice',
  'Self-Discovery',
  'Self-Improvement',
  'Self-Love',
  'Service',
  'Silence',
  'Simplicity',
  'Sincerity',
  'Spirituality',
  'Strength',
  'Success',
  'Teamwork',
  'Time',
  'Travel',
  'Trust',
  'Unity',
  'Value',
  'Vision',
  'Wealth',
  'Wellness',
  'Wisdom',
  'Wisdom of Age',
  'Worry & Anxiety',
  'Youth',
  'Uncategorized',
];

// Add this: Emoji map for categories
const Map<String, String> kCategoryEmoji = {
  'All': '🌸',
  'Action': '⚡️',
  'Adventure': '🏔️',
  'Art': '🖼️',
  'Balance': '🤹',
  'Belief': '🙌',
  'Change': '🔄',
  'Charity': '🎁',
  'Childhood': '🧸',
  'Community': '🏘️',
  'Confidence': '😎',
  'Courage': '🦁',
  'Creativity & Inspiration': '🎨',
  'Culture': '🎭',
  'Decision': '🔀',
  'Determination': '⛰️',
  'Discipline': '🥋',
  'Diversity': '🌈',
  'Dreams': '🌙',
  'Education': '🎓',
  'Empathy': '💗',
  'Endings': '🌇',
  'Equality': '🟰',
  'Faith': '🕍',
  'Family': '👨‍👩‍👧‍👦',
  'Focus': '🧐',
  'Forging Ahead': '🚀',
  'Forgiveness': '🫂',
  'Freedom': '🗽',
  'Friendship': '👫',
  'Giving': '💝',
  'Gratitude': '🙏',
  'Growth': '🌿',
  'Hard Work': '💪',
  'Happiness & Joy': '😊',
  'Health': '🍎',
  'Hope': '🌅',
  'Honesty': '🪞',
  'Humility': '🪶',
  'Humor': '😂',
  'Imagination': '🦋',
  'Inclusion': '🧑‍🤝‍🧑',
  'Innovation': '💡',
  'Integrity': '🦾',
  'Justice': '⚖️',
  'Kindness': '🤗',
  'Leadership': '👑',
  'Learning': '📖',
  'Legacy': '🏛️',
  'Life': '🌱',
  'Listening': '👂',
  'Love': '💖',
  'Memories': '📷',
  'Mindfulness': '🧘',
  'Mindfulness & Letting Go': '🍃',
  'Mindset': '🧠',
  'Motivation & Achievement': '🏆',
  'Music': '🎵',
  'Natural': '🌳',
  'New Beginnings': '🥚',
  'Opportunity': '🪟',
  'Overcoming Obstacles': '⛷️',
  'Parenting': '🧑‍🍼',
  'Passion': '🔥',
  'Patience': '⏳',
  'Peace': '🕊️',
  'Peace & Inner Calm': '☮️',
  'Perseverance': '🛤️',
  'Philosophy': '📜',
  'Positivity': '🌞',
  'Prosperity': '🪙',
  'Purpose': '🎯',
  'Reflection': '🔮',
  'Relationships & Connection': '💞',
  'Resilience': '🌵',
  'Responsibility': '🧑‍💼',
  'Risk': '🎲',
  'Sacrifice': '⚰️',
  'Self-Discovery': '🧭',
  'Self-Improvement': '🔝',
  'Self-Love': '💓',
  'Service': '🧹',
  'Silence': '🔇',
  'Simplicity': '🔹',
  'Sincerity': '🫶',
  'Spirituality': '🕉️',
  'Strength': '🦾',
  'Success': '🏅',
  'Teamwork': '🤼',
  'Time': '⏰',
  'Travel': '✈️',
  'Trust': '🗝️',
  'Unity': '🔗',
  'Value': '💎',
  'Vision': '🔭',
  'Wealth': '💸',
  'Wellness': '🥦',
  'Wisdom': '🦉',
  'Wisdom of Age': '👵',
  'Worry & Anxiety': '😟',
  'Youth': '🧑',
  'Uncategorized': '✨',
};
